version: "3.7"

services:
  oficialmed-pwa:
    image: oficialmedpro/oficialmed-pwa:latest
    
    networks:
      - OficialMed
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.http.routers.oficialmed_pwa.rule=Host(`bi.oficialmed.com.br`)
        - traefik.http.routers.oficialmed_pwa.entrypoints=websecure
        - traefik.http.routers.oficialmed_pwa.tls.certresolver=letsencryptresolver
        - traefik.http.services.oficialmed_pwa.loadbalancer.server.port=80
        - traefik.http.services.oficialmed_pwa.loadbalancer.passHostHeader=true
        - traefik.http.routers.oficialmed_pwa.service=oficialmed_pwa

networks:
  OficialMed:
    external: true
    name: OficialMed