version: "3.7"

services:

## --------------------------- POSTGRESQL CHATWOOT --------------------------- ##

  postgres-chatwoot:
    image: postgres:14
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

    volumes:
      - postgres_chatwoot_data:/var/lib/postgresql/data

    networks:
      - OficialMed

    environment:
      ## 🔑 Senha do Postgres 
      - POSTGRES_PASSWORD=a5895d0e44e68fc82c13e7d6a92313dd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chatwoot

      ## 🌎 Timezone
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

## --------------------------- REDIS CHATWOOT --------------------------- ##

  redis-chatwoot:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass a5895d0e44e68fc82c13e7d6a92313dd

    volumes:
      - redis_chatwoot_data:/data

    networks:
      - OficialMed

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

## --------------------------- CHATWOOT WEB --------------------------- ##

  chatwoot-web:
    image: chatwoot/chatwoot:latest
    restart: unless-stopped

    volumes:
      - chatwoot_data:/app/storage
      - chatwoot_logs:/app/log

    networks:
      - OficialMed

    environment:
      ## 🗄️ Database Configuration
      - POSTGRES_HOST=postgres-chatwoot
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=a5895d0e44e68fc82c13e7d6a92313dd

      ## 🔴 Redis Configuration
      - REDIS_URL=redis://:a5895d0e44e68fc82c13e7d6a92313dd@redis-chatwoot:6379

      ## 🌐 App Configuration
      - RAILS_ENV=production
      - SECRET_KEY_BASE=$(openssl rand -hex 64)
      - FRONTEND_URL=https://chat.oficialmed.com.br
      - INSTALLATION_NAME="OficialMed Chat"
      - INSTALLATION_VERSION=2.0.0

      ## 📧 Mail Configuration (configure conforme necessário)
      - MAILER_SENDER_EMAIL=
      - SMTP_ADDRESS=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true

      ## 🔐 Security
      - ENABLE_ACCOUNT_SIGNUP=true
      - ENABLE_GOOGLE_OAUTH=false
      - ENABLE_FACEBOOK_OAUTH=false
      - ENABLE_TWITTER_OAUTH=false

      ## 🌎 Timezone
      - TZ=America/Sao_Paulo

    depends_on:
      - postgres-chatwoot
      - redis-chatwoot

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # Router principal (HTTPS) - Chatwoot
        - traefik.http.routers.chatwoot-web.rule=Host(`chat.oficialmed.com.br`)
        - traefik.http.routers.chatwoot-web.entrypoints=websecure
        - traefik.http.routers.chatwoot-web.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot-web.service=chatwoot-web
        - traefik.http.services.chatwoot-web.loadbalancer.server.port=3000
        - traefik.http.services.chatwoot-web.loadbalancer.passHostHeader=true

        # Redirecionar HTTP -> HTTPS - Chatwoot
        - traefik.http.routers.chatwoot-web-http.rule=Host(`chat.oficialmed.com.br`)
        - traefik.http.routers.chatwoot-web-http.entrypoints=web
        - traefik.http.routers.chatwoot-web-http.middlewares=force-https-chatwoot
        - traefik.http.middlewares.force-https-chatwoot.redirectscheme.scheme=https

        # (Opcional) redirecionar www -> raiz - Chatwoot
        - traefik.http.routers.chatwoot-web-www.rule=Host(`www.chat.oficialmed.com.br`)
        - traefik.http.routers.chatwoot-web-www.entrypoints=websecure
        - traefik.http.routers.chatwoot-web-www.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot-web-www.middlewares=chatwoot-web-www2root
        - traefik.http.middlewares.chatwoot-web-www2root.redirectregex.regex=^https://www\\.(.*)
        - traefik.http.middlewares.chatwoot-web-www2root.redirectregex.replacement=https://$${1}
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

## --------------------------- CHATWOOT WORKER --------------------------- ##

  chatwoot-worker:
    image: chatwoot/chatwoot:latest
    restart: unless-stopped

    volumes:
      - chatwoot_data:/app/storage
      - chatwoot_logs:/app/log

    networks:
      - OficialMed

    environment:
      ## 🗄️ Database Configuration
      - POSTGRES_HOST=postgres-chatwoot
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=a5895d0e44e68fc82c13e7d6a92313dd

      ## 🔴 Redis Configuration
      - REDIS_URL=redis://:a5895d0e44e68fc82c13e7d6a92313dd@redis-chatwoot:6379

      ## 🌐 App Configuration
      - RAILS_ENV=production
      - SECRET_KEY_BASE=$(openssl rand -hex 64)
      - FRONTEND_URL=https://chat.oficialmed.com.br

      ## 🌎 Timezone
      - TZ=America/Sao_Paulo

    command: bundle exec sidekiq -C config/sidekiq.yml

    depends_on:
      - postgres-chatwoot
      - redis-chatwoot

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

## --------------------------- VOLUMES --------------------------- ##

volumes:
  postgres_chatwoot_data:
    driver: local
  redis_chatwoot_data:
    driver: local
  chatwoot_data:
    driver: local
  chatwoot_logs:
    driver: local

## --------------------------- NETWORKS --------------------------- ##

networks:
  OficialMed:
    external: true
    name: OficialMed
