version: "3.7"

services:

## --------------------------- POSTGRESQL KRAYIN CRM --------------------------- ##

  postgres-krayin:
    image: postgres:14
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

    volumes:
      - postgres_krayin_data:/var/lib/postgresql/data

    networks:
      - OficialMed

    environment:
      ## 🔑 Senha do Postgres 
      - POSTGRES_PASSWORD=a5895d0e44e68fc82c13e7d6a92313dd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=krayin_crm

      ## 🌎 Timezone
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

## --------------------------- REDIS KRAYIN CRM --------------------------- ##

  redis-krayin:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass a5895d0e44e68fc82c13e7d6a92313dd

    volumes:
      - redis_krayin_data:/data

    networks:
      - OficialMed

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

## --------------------------- KRAYIN CRM --------------------------- ##

  krayin-crm:
    image: webkul/krayin:latest
    restart: unless-stopped
    entrypoint: >
      bash -c "
      php artisan config:clear &&
      php artisan route:clear &&
      php artisan view:clear &&
      php artisan cache:clear &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan optimize &&
      /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisor.conf
      "

    volumes:
      - krayin_crm_data:/app/storage
      - krayin_crm_uploads:/app/public/uploads
      - krayin_crm_public:/app/public

    networks:
      - OficialMed

    environment:
      ## 🗄️ Database Configuration
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres-krayin
      - DB_PORT=5432
      - DB_DATABASE=krayin_crm
      - DB_USERNAME=postgres
      - DB_PASSWORD=a5895d0e44e68fc82c13e7d6a92313dd

      ## 🔴 Redis Configuration
      - REDIS_HOST=redis-krayin
      - REDIS_PASSWORD=a5895d0e44e68fc82c13e7d6a92313dd
      - REDIS_PORT=6379

      ## 🌐 App Configuration
      - APP_NAME="Krayin CRM"
      - APP_ENV=production
      - APP_KEY=base64:Y2hhbmdlLXRoaXMta2V5LXRvLXNvbWV0aGluZy1zZWN1cmUtYW5kLXVuaXF1ZQ==
      - APP_DEBUG=true
      - APP_URL=https://crm.oficialmed.com.br
      - ASSET_URL=https://crm.oficialmed.com.br
      - FORCE_HTTPS=true
      - TRUSTED_PROXIES=*
      - HTTPS_ONLY=true
      - SCHEME=https
      - HTTP_HOST=crm.oficialmed.com.br
      - SERVER_NAME=crm.oficialmed.com.br

      ## 📧 Mail Configuration (configure conforme necessário)
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=tls

      ## 🌎 Timezone
      - TZ=America/Sao_Paulo

    depends_on:
      - postgres-krayin
      - redis-krayin

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # Router principal (HTTPS) - Krayin CRM
        - traefik.http.routers.krayin-crm.rule=Host(`crm.oficialmed.com.br`)
        - traefik.http.routers.krayin-crm.entrypoints=websecure
        - traefik.http.routers.krayin-crm.tls.certresolver=letsencryptresolver
        - traefik.http.routers.krayin-crm.service=krayin-crm
        - traefik.http.routers.krayin-crm.middlewares=secure-headers
        - traefik.http.services.krayin-crm.loadbalancer.server.port=80
        - traefik.http.services.krayin-crm.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.secure-headers.headers.customRequestHeaders.X-Forwarded-Proto=https
        - traefik.http.middlewares.secure-headers.headers.customRequestHeaders.X-Forwarded-Port=443
        - traefik.http.middlewares.secure-headers.headers.forceSTSHeader=true
        - traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000

        # Redirecionar HTTP -> HTTPS - Krayin CRM
        - traefik.http.routers.krayin-crm-http.rule=Host(`crm.oficialmed.com.br`)
        - traefik.http.routers.krayin-crm-http.entrypoints=web
        - traefik.http.routers.krayin-crm-http.middlewares=force-https
        - traefik.http.middlewares.force-https.redirectscheme.scheme=https

        # (Opcional) redirecionar www -> raiz - Krayin CRM
        - traefik.http.routers.krayin-crm-www.rule=Host(`www.crm.oficialmed.com.br`)
        - traefik.http.routers.krayin-crm-www.entrypoints=websecure
        - traefik.http.routers.krayin-crm-www.tls.certresolver=letsencryptresolver
        - traefik.http.routers.krayin-crm-www.middlewares=krayin-crm-www2root
        - traefik.http.middlewares.krayin-crm-www2root.redirectregex.regex=^https://www\\.(.*)
        - traefik.http.middlewares.krayin-crm-www2root.redirectregex.replacement=https://$${1}
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

## --------------------------- VOLUMES --------------------------- ##

volumes:
  postgres_krayin_data:
    driver: local
  redis_krayin_data:
    driver: local
  krayin_crm_data:
    driver: local
  krayin_crm_uploads:
    driver: local
  krayin_crm_public:
    driver: local

## --------------------------- NETWORKS --------------------------- ##

networks:
  OficialMed:
    external: true
    name: OficialMed
