version: "3.7"
services:

## --------------------------- N8N --------------------------- ##

  n8n:
    image: n8nio/n8n:latest ## Versão do n8n

    networks:
      - OficialMed ## Nome da rede interna

    environment:
    ## 🗄️ Dados do Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=a5895d0e44e68fc82c13e7d6a92313dd

    ## 🔐 Encryption key (gere uma chave única: openssl rand -hex 32)
      - N8N_ENCRYPTION_KEY=83d8442f4011a5908b9bc882520d3352a1b2c3d4e5f6g7h8

    ## 🌐 URLs do n8n
      - N8N_HOST=workflows.oficialmed.com.br
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://webhook.oficialmed.com.br/

    ## 👤 Credenciais do Admin (primeiro acesso)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=OfiCialMed2025!

    ## 📧 Dados do SMTP
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=465
      - N8N_SMTP_USER=mkt.oficialmed@gmail.com
      - N8N_SMTP_PASS=Joao1633@@
      - N8N_SMTP_SENDER=mkt.oficialmed@gmail.com
      - N8N_SMTP_SSL=true

    ## 🗃️ Configurações gerais
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=true
      - N8N_VERSION_NOTIFICATIONS_ENABLED=true
      - N8N_TEMPLATES_ENABLED=true
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console

    ## 📂 Configurações de execução
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=336 ## Mantém execuções por 14 dias

    ## ⏱️ Timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo

    volumes:
      - n8n_data:/home/node/.n8n

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      labels:
        - io.portainer.accesscontrol.users=admin
        
        ## Configuração para workflows.oficialmed.com.br (interface principal)
        - traefik.enable=true
        - traefik.http.routers.n8n_editor.rule=Host(`workflows.oficialmed.com.br`)
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.tls.certresolver=letsencryptresolver
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
        - traefik.http.services.n8n_editor.loadbalancer.passHostHeader=true
        - traefik.http.routers.n8n_editor.service=n8n_editor
        
        ## Configuração para webhook.oficialmed.com.br (webhooks)
        - traefik.http.routers.n8n_webhook.rule=Host(`webhook.oficialmed.com.br`)
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.tls.certresolver=letsencryptresolver
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678

## --------------------------- ORION --------------------------- ##

volumes:
  n8n_data:
    driver: local

networks:
  OficialMed: ## Nome da rede interna
    external: true
    name: OficialMed ## Nome da rede interna

