version: "3.7"

services:
  oportunidades-sync-api:
    image: oficialmedpro/oportunidades-sync-api:latest
    networks:
      - OficialMed
    environment:
      - NODE_ENV=production
      - PORT=5001

      # Supabase (via secrets com NOMES NOVOS)
      - SUPABASE_URL_FILE=/run/secrets/OPP_SUPABASE_URL
      - SUPABASE_KEY_FILE=/run/secrets/OPP_SUPABASE_KEY

      # SprintHub (via secrets com NOMES NOVOS)
      - SPRINTHUB_BASE_URL_FILE=/run/secrets/OPP_SPRINTHUB_BASE_URL
      - SPRINTHUB_INSTANCE_FILE=/run/secrets/OPP_SPRINTHUB_INSTANCE
      - SPRINTHUB_TOKEN_FILE=/run/secrets/OPP_SPRINTHUB_TOKEN

      # API Token (direto, sem secret)
      - API_TOKEN=oportunidades-sync-2025-mN7pQ2rS5tU9wV3xY6zA0bC4dE8fG1hI

    secrets:
      - OPP_SUPABASE_URL
      - OPP_SUPABASE_KEY
      - OPP_SPRINTHUB_BASE_URL
      - OPP_SPRINTHUB_INSTANCE
      - OPP_SPRINTHUB_TOKEN

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true

        # Router principal (HTTPS)
        - traefik.http.routers.oportunidades-sync.rule=Host(`sincro.oficialmed.com.br`) && PathPrefix(`/oportunidades`)
        - traefik.http.routers.oportunidades-sync.entrypoints=websecure
        - traefik.http.routers.oportunidades-sync.tls.certresolver=letsencryptresolver

        # Serviço apontando para a porta 5001 do container
        - traefik.http.services.oportunidades-sync.loadbalancer.server.port=5001
        - traefik.http.services.oportunidades-sync.loadbalancer.passHostHeader=true
        - traefik.http.routers.oportunidades-sync.service=oportunidades-sync

        # Middleware para remover /oportunidades do path
        - traefik.http.routers.oportunidades-sync.middlewares=opp-stripprefix
        - traefik.http.middlewares.opp-stripprefix.stripprefix.prefixes=/oportunidades

        # Redirecionar HTTP -> HTTPS
        - traefik.http.routers.oportunidades-sync-http.rule=Host(`sincro.oficialmed.com.br`) && PathPrefix(`/oportunidades`)
        - traefik.http.routers.oportunidades-sync-http.entrypoints=web
        - traefik.http.routers.oportunidades-sync-http.middlewares=force-https-opp
        - traefik.http.middlewares.force-https-opp.redirectscheme.scheme=https

networks:
  OficialMed:
    external: true
    name: OficialMed

secrets:
  OPP_SUPABASE_URL:
    external: true
  OPP_SUPABASE_KEY:
    external: true
  OPP_SPRINTHUB_BASE_URL:
    external: true
  OPP_SPRINTHUB_INSTANCE:
    external: true
  OPP_SPRINTHUB_TOKEN:
    external: true









