version: "3.7"

services:
  sync-opportunities-api:
    image: oficialmedpro/sync-opportunities-api:latest
    networks:
      - OficialMed
    environment:
      - NODE_ENV=production
      - PORT=3002

      # Supabase (via secrets)
      - SUPABASE_URL_FILE=/run/secrets/SYNC_SUPABASE_URL
      - SUPABASE_KEY_FILE=/run/secrets/SYNC_SUPABASE_KEY

      # SprintHub (via secrets)
      - SPRINTHUB_BASE_URL_FILE=/run/secrets/SYNC_SPRINTHUB_BASE_URL
      - SPRINTHUB_INSTANCE_FILE=/run/secrets/SYNC_SPRINTHUB_INSTANCE
      - SPRINTHUB_TOKEN_FILE=/run/secrets/SYNC_SPRINTHUB_TOKEN

      # API Token (direto, sem secret)
      - API_TOKEN=sync-opportunities-2025-bC4dE8fG0hI3jL6nO9qR2sT5uV8wX1yZ

    secrets:
      - SYNC_SUPABASE_URL
      - SYNC_SUPABASE_KEY
      - SYNC_SPRINTHUB_BASE_URL
      - SYNC_SPRINTHUB_INSTANCE
      - SYNC_SPRINTHUB_TOKEN

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true

        # Router para /oportunidades (HTTPS)
        - traefik.http.routers.sync-opportunities.rule=Host(`sincro.oficialmed.com.br`) && PathPrefix(`/oportunidades`)
        - traefik.http.routers.sync-opportunities.entrypoints=websecure
        - traefik.http.routers.sync-opportunities.tls.certresolver=letsencryptresolver

        # Serviço apontando para a porta 3002 do container
        - traefik.http.services.sync-opportunities.loadbalancer.server.port=3002
        - traefik.http.services.sync-opportunities.loadbalancer.passHostHeader=true
        - traefik.http.routers.sync-opportunities.service=sync-opportunities

        # Middleware para remover /oportunidades do path
        - traefik.http.routers.sync-opportunities.middlewares=opportunities-stripprefix
        - traefik.http.middlewares.opportunities-stripprefix.stripprefix.prefixes=/oportunidades

        # Health check
        - traefik.http.routers.sync-opportunities-health.rule=Host(`sincro.oficialmed.com.br`) && Path(`/oportunidades/health`)
        - traefik.http.routers.sync-opportunities-health.entrypoints=websecure
        - traefik.http.routers.sync-opportunities-health.tls.certresolver=letsencryptresolver
        - traefik.http.routers.sync-opportunities-health.service=sync-opportunities

networks:
  OficialMed:
    external: true
    name: OficialMed

secrets:
  SYNC_SUPABASE_URL:
    external: true
  SYNC_SUPABASE_KEY:
    external: true
  SYNC_SPRINTHUB_BASE_URL:
    external: true
  SYNC_SPRINTHUB_INSTANCE:
    external: true
  SYNC_SPRINTHUB_TOKEN:
    external: true

