-- Criação da tabela de logs SprintHub
create table if not exists api.sprinthub_sync_logs (
  id                bigint generated by default as identity primary key,
  entity_type       text    not null,
  entity_id         text    not null,
  action            text    not null,
  signature         text,
  status            text    not null default 'pending',
  payload           jsonb,
  response          jsonb,
  error_message     text,
  metadata          jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists sprinthub_sync_logs_entity_idx
  on api.sprinthub_sync_logs (entity_type, entity_id);

create unique index if not exists sprinthub_sync_logs_signature_unique
  on api.sprinthub_sync_logs (signature)
  where signature is not null;

create trigger sprinthub_sync_logs_set_updated_at
  before update on api.sprinthub_sync_logs
  for each row
  execute procedure api.set_updated_at();






