-- Criar tabela para configuração de dias úteis do mês
CREATE TABLE IF NOT EXISTS api.cockpit_dias_uteis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER NOT NULL,
    mes INTEGER NOT NULL CHECK (mes >= 1 AND mes <= 12),
    dias_uteis_total INTEGER NOT NULL CHECK (dias_uteis_total >= 0),
    dias_uteis_restantes INTEGER CHECK (dias_uteis_restantes >= 0),
    ultima_atualizacao TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by INTEGER,
    updated_by INTEGER,
    
    -- Garantir que só existe um registro por mês/ano
    CONSTRAINT unique_ano_mes UNIQUE (ano, mes)
);

COMMENT ON TABLE api.cockpit_dias_uteis IS 'Configuração de dias úteis do mês para cálculo de meta acumulada no Cockpit';
COMMENT ON COLUMN api.cockpit_dias_uteis.ano IS 'Ano (ex: 2025)';
COMMENT ON COLUMN api.cockpit_dias_uteis.mes IS 'Mês (1-12)';
COMMENT ON COLUMN api.cockpit_dias_uteis.dias_uteis_total IS 'Total de dias úteis do mês (preenchido manualmente pelo gerente)';
COMMENT ON COLUMN api.cockpit_dias_uteis.dias_uteis_restantes IS 'Dias úteis restantes do mês (calculado automaticamente ou editado manualmente)';

-- Habilitar RLS
ALTER TABLE api.cockpit_dias_uteis ENABLE ROW LEVEL SECURITY;

-- Criar políticas para permitir acesso público (similar às outras tabelas do cockpit)
CREATE POLICY "Allow all operations for cockpit_dias_uteis"
ON api.cockpit_dias_uteis
FOR ALL
TO public
USING (true)
WITH CHECK (true);

-- Conceder permissões
GRANT ALL PRIVILEGES ON TABLE api.cockpit_dias_uteis TO PUBLIC;
GRANT ALL PRIVILEGES ON TABLE api.cockpit_dias_uteis TO anon;
GRANT ALL PRIVILEGES ON TABLE api.cockpit_dias_uteis TO authenticated;

-- Criar índice para buscas rápidas por ano/mês
CREATE INDEX idx_cockpit_dias_uteis_ano_mes ON api.cockpit_dias_uteis(ano, mes);

